### ISSUE TITLE
[Feat] Add support for nvim-notify

### ISSUE THREAD

**Issue by vihu** [ribru17/bamboo.nvim#10]
Hello,

I noticed that there is no support for color highlights for [nvim-notify](https://github.com/rcarriga/nvim-notify). Would be nice to implement those to avoid unnecessary warnings for missing highlights.

Here's how [kanagawa](https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/highlights/plugins.lua#L89) does it for reference.

**Comment by ribru17** [comment]
Thank you!
