### ISSUE TITLE
[Bug] code_style does not seem to be honored correctly

### ISSUE THREAD

**Issue by vihu** [ribru17/bamboo.nvim#13]
Hello,

Perhaps it's just my config but it appears that `code_style` config block is not quite honored as expected. For example, here's my config:

```lua
return {
	"ribru17/bamboo.nvim",
	lazy = false,
	enabled = true,
	cond = true,
	priority = 1000,
	config = function()
		require("bamboo").setup({
			transparent = true,
			dim_inactive = true,
			term_colors = true,
			code_style = {
				comments = "none",
				conditionals = "none",
				keywords = "none",
				functions = "none",
				strings = "none",
				variables = "none",
			},
			lualine = {
				transparent = true,
			},
			highlights = {
				["@comment"] = { fg = "$grey" },
			},
		})
		vim.o.background = "dark"
		require("bamboo").load()
	end,
}
```

And notice the following (I haven't underlined everything but you get the idea):

![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/a1f3c532-f9c0-40c6-aee0-8b954833ff52)

**Comment by ribru17** [comment]
Right now this is the expected behavior, as namespaces (light blue) and parameters (orange red) do not fall under any of the code style categories. But perhaps I could extend `code_style` to have `parameters` and `namespaces` keys. Would you find this to be an acceptable solution?

**Comment by vihu** [comment]
> Right now this is the expected behavior, as namespaces (light blue) and parameters (orange red) do not fall under any of the code style categories. But perhaps I could extend `code_style` to have `parameters` and `namespaces` keys. Would you find this to be an acceptable solution?

Yes please, that would be great.

**Comment by ribru17** [comment]
Try now with `parameters` and `namespaces` keys for `code_style`
