### ISSUE TITLE
create a separate colorscheme file for each colorscheme

### ISSUE THREAD

**Issue by aikow** [ribru17/bamboo.nvim#15]
Hey, thanks for creating such a nice (and new) theme. Would you be opposed to having a separate colorscheme file for each of the variants? I often find myself wanting to quickly switch between different variants of a colorscheme, and being able to just use `colo bamboo-vulgaris`, `colo bamboo-light`, or `colo bamboo-multiplex` is a bit short than typing out `lua require("bamboo").toggle()`. If you're not opposed, I can create a PR later. If you'd prefer to keep it simple, just close this MR :)

**Comment by ribru17** [comment]
I'm not opposed to this at all, and a PR would be great! Thanks for bringing this up!
