### ISSUE TITLE
Different background for end-of-file rows with dim_inactive. 

### ISSUE THREAD

**Issue by lkhphuc** [ribru17/bamboo.nvim#17]
Hi, when I turned on dim_inactive, the dimmed windows have different background color for text line and empty lines at the end of files.
It seems these lines are not dimmed.

Inactive win left, active win right.
![Screenshot 2023-12-04 at 14 46 47](https://github.com/ribru17/bamboo.nvim/assets/12573521/55318853-f3ae-440f-ba2f-1736c09b3e00)

**Comment by ribru17** [comment]
Thanks for the report! Should be fixed now
