### ISSUE TITLE
[Request] Improve contrast for the light theme

### ISSUE THREAD

**Issue by vihu** [ribru17/bamboo.nvim#20]
I was wondering if you'd consider spending some time in improving the contrast for the light palette. I'll just post some screenshot here:

Notice the very light blue color here:
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/0c4a3c66-ba4e-44af-b410-eaf895b31d23)

This is my personal opinion but the choice of light golden yellow for struct name/type value also seems faint:
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/2cd345e5-792d-4bc3-8a27-5229612dde60)

Similarly (light orange, light golden yellow, very light blue) for imports:
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/525cc9a5-bbcf-44c1-b4ad-be9a44095307)

You really don't have to do this, I just wanted to bring this to your attention since I truly appreciate your choice of colors for the dark palette the light one could also use some extra love :). Thanks!

**Comment by ribru17** [comment]
Thank you for the report! I agree with you that the contrast is not good enough. I took a stab at this a few weeks ago but couldn't figure out something that I was happy with. I think maybe I should look to other light themes for examples. It was difficult to get a lighter blue that was both contrasty and distinctive from the regular blue. If you have any color suggestions (or general suggestions) I am all ears! I will take another stab at this soon either way. Thank you!

**Comment by vihu** [comment]
> Thank you for the report! I agree with you that the contrast is not good enough. I took a stab at this a few weeks ago but couldn't figure out something that I was happy with. I think maybe I should look to other light themes for examples. It was difficult to get a lighter blue that was both contrasty and distinctive from the regular blue. If you have any color suggestions (or general suggestions) I am all ears! I will take another stab at this soon either way. Thank you!

Yeah, its quite hard to get light colors correct imo. The only well supported light colorscheme I have liked so far is `dayfox` which is part of [nightfox](https://github.com/EdenEast/nightfox.nvim).

Screenshots using dayfox:
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/ee6196ac-003e-40db-b22a-832a69460770)
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/a533e1ea-20e1-4b32-a10c-0af00ce77f77)
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/37b91f33-9777-4558-8147-f6ef8aa39467)

Other light colorschemes which do a relatively decent job in my opinion:
- https://github.com/Verf/deepwhite.nvim (missing support for common plugins)
- https://github.com/miikanissi/modus-themes.nvim (way too much contrast)
- https://github.com/rebelot/kanagawa.nvim (too yellow, suffers from low contrast as well)
- https://github.com/catppuccin/nvim (latte flavor, way too much red/orange, good contrast though)

My absolute favorite though is https://github.com/yorickpeterse/vim-paper because it's very readable in brighter conditions, sadly it doesn't have an up-to-date implementation for nvim and very minimal plugin support but the palette choice is fantastic.

**Comment by ribru17** [comment]
Thank you! I will try and take inspiration from these, especially vim-paper.

**Comment by ribru17** [comment]
Would you mind checking out [this branch](https://github.com/ribru17/bamboo.nvim/tree/light_contrast) when you get a chance? I tried to improve the contrast a bit and I think it looks a lot better, without compromising the style. Let me know if you think it still needs changes. Also do you think the orange color needs the same treatment? Thank you for your help!

**Comment by vihu** [comment]
> Would you mind checking out [this branch](https://github.com/ribru17/bamboo.nvim/tree/light_contrast) when you get a chance? I tried to improve the contrast a bit and I think it looks a lot better, without compromising the style. Let me know if you think it still needs changes. Also do you think the orange color needs the same treatment? Thank you for your help!

I put some general comments in this screenshot:
![image](https://github.com/ribru17/bamboo.nvim/assets/3199183/85ff4de4-0a08-4e3f-84e0-7c3fac47480a)

**Comment by ribru17** [comment]
Thank you so much for your time and input, I really appreciate it. I think I have managed to improve on every pain point you have given (and agreed with all of them as well), except for the one about comments. I did give a small mention [here](https://github.com/ribru17/bamboo.nvim/blob/dbcc1c96be0c25f95e52e9acda67e62027ac30d7/README.md?plain=1#L194) on how to get traditional comment styling but maybe it should be more clear. My mindset with this theme has always been leaning towards the notion that comments are for reading (and should stand out as such). I never really was a fun of the low-contrast comment colors on most other themes; I feel like that makes more sense when treating comments as just commented-out code (which is in general bad practice)

**Comment by vihu** [comment]
> Thank you so much for your time and input, I really appreciate it. I think I have managed to improve on every pain point you have given (and agreed with all of them as well), except for the one about comments. I did give a small mention [here](https://github.com/ribru17/bamboo.nvim/blob/dbcc1c96be0c25f95e52e9acda67e62027ac30d7/README.md?plain=1#L194) on how to get traditional comment styling but maybe it should be more clear. My mindset with this theme has always been leaning towards the notion that comments are for reading (and should stand out as such). I never really was a fun of the low-contrast comment colors on most other themes; I feel like that makes more sense when treating comments as just commented-out code (which is in general bad practice). Anyways let me know if you think anything needs more improvement, or if you disagree about anything. Thank you again for your insight :)

The latest commit on your branch looks great! Don't have any more suggestions :)
As for the comment highlight, I just set it to grey as you mentioned in the README so all good there. Thank you!

**Comment by ribru17** [comment]
Glad to hear; thank you again so much for all the help!
