### ISSUE TITLE
Package for luarocks

### ISSUE THREAD

**Issue by ambaradan** [ribru17/bamboo.nvim#27]
Hello and congratulations for the theme, it is very nice.
I am using it in a Neovim setup dedicated to writing documentation in Markdown. However, my configuration uses [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) for plugin management and I was wondering if it would be possible to have it available natively on [luarocks.org](https://luarocks.org/). I currently install it using the *rocks-git.nvim* utility but having it as a native *luarocks* package would be really wonderful.
I am not so experienced that I can help you, I know that you have to create a *spec* file and publish it but I have no experience with that, I think the developers of Rocks.nvim would certainly be happy to help you.
If you want to take a look at the IDE project for Markdown:

```txt
https://github.com/ambaradan/rocksmarker
```

Thanks and I hope I'm not disturbing

**Comment by ribru17** [comment]
Thank you! I have no experience with lua rocks but I have created a branch called `rockspec` with a rockspec file I guessed at creating, based off one for `tokyonight` in a moon rocks project. Please try it and let me know if it works! :)

**Comment by ambaradan** [comment]
I have already posted it, you can find it at *luarocks.org* and you can install it with:

```txt
:Rocks install bamboo.nvim
```

the spec file is as follows:

```lua
local git_ref = "d38c50257d9fb16b17050569b29d777b1f2503ee"
local modrev = "scm"
local specrev = "1"

local repo_url = "https://github.com/ribru17/bamboo.nvim"

rockspec_format = "3.0"
package = "bamboo.nvim"
version = modrev .. "-" .. specrev

description = {
	summary = "Dark green theme for Neovime",
	detailed = "",
	labels = { "neovim" },
	homepage = "https://github.com/ribru17/bamboo.nvim",
	license = "MIT",
}

dependencies = { "lua >= 5.1" }

test_dependencies = {}

source = {
	url = repo_url .. "/archive/" .. git_ref .. ".zip",
	dir = "bamboo.nvim-" .. "d38c50257d9fb16b17050569b29d777b1f2503ee",
}

if modrev == "scm" or modrev == "dev" then
	source = {
		url = repo_url:gsub("https", "git"),
	}
end

build = {
	type = "builtin",
	copy_directories = { "colors" },
}
```

**Comment by ambaradan** [comment]
If you want to handle it yourself I can always delete my module.

**Comment by ribru17** [comment]
Ah great! Mine looks basically the same I think. Just to clarify, all you would need me to do is put that file in this repo (at the root)?

**Comment by ambaradan** [comment]
I really think your *rockspec* file is perfect, even better with the use of `dir = 'bamboo.nvim-' .. git_ref,` when you want tell me I delete the module from luarocks so you can upload it

**Comment by ambaradan** [comment]
No it has to be entered into *luarocks.org* from the web interface or directly from the command line with luarocks, you have to log into luarocks.org (even with your github account) and create an API key to upload from the terminal.
https://github.com/luarocks/luarocks/wiki/Documentation

**Comment by ambaradan** [comment]
luarocks creates a binary package from the information given through the spec file, and takes care of uploading it and updating your account on luarocks.org, example:

```txt
luarocks upload --api-key=YOUR-KEY bamboo.nvim-scm-1.rockspec
```

**Comment by ribru17** [comment]
Thanks, I have uploaded it :)

https://luarocks.org/modules/ribru17/bamboo.nvim

I did it through the web interface, hopefully the result is the same

**Comment by ambaradan** [comment]
I'm going to delete mine now and try, I'll let you know later.

**Comment by ambaradan** [comment]
@ribru17 It seems to have failed, I can't find the module, I saw that it is there but it seems to have not been published correctly. I have never used the web interface, if you want I will give your spec a try with my account.

**Comment by ribru17** [comment]
Weird... could there be a delay upon publishing?

**Comment by ambaradan** [comment]
No it is pretty much immediate, you should see it in the new packages on the home page.

**Comment by ambaradan** [comment]
![missing](https://github.com/user-attachments/assets/32f8f77a-e8ce-4483-8e44-58cf975e31e4)

**Comment by ribru17** [comment]
I see. Try again now at https://luarocks.org/modules/ribru17/bamboo.nvim, I uploaded with the CLI this time

**Comment by ambaradan** [comment]
Your *spec* works fine, it must be a problem with the web interface. I'll leave my form for the time being for people who might be using my configuration.
![good](https://github.com/user-attachments/assets/f4bda6ac-66ec-43a5-8435-24d02f9a20f9)

**Comment by ambaradan** [comment]
Removed mine now let's see what happens!

**Comment by ambaradan** [comment]
There seems to be some problem in your system because it's not there yet, if you agree I'll leave my module that I need for configuration and once the problems are solved we'll pass it to your account.

**Comment by ambaradan** [comment]
Done
