### ISSUE TITLE
horizontal split border style

### ISSUE THREAD

**Issue by huashengdun** [ribru17/bamboo.nvim#3]
Hi, 

I like your theme,  it is great.
So my question is how to change the border style (like width or color) when the window is split horizontally.

Thanks.

**Comment by ribru17** [comment]
Thanks glad you like it. You can change the color of a window split separator with the `WinSeparator` highlight, e.g.
```lua
require('bamboo').setup {
  highlights = {
    ['WinSeparator'] = { fg = '$red' },
  },
}
```
or if you mean to change the status bar that separates horizontal splits you can try something like `:let &statusline='%#Red# '` which makes the status bar red.
