### ISSUE TITLE
Wezterm Integration

### ISSUE THREAD

**Issue by ribru17** [ribru17/bamboo.nvim#4]
Hi @wez I was wondering if it would be possible to sync this theme with Wezterm if you ever get the chance? I added the necessary `toml` files in the `extras/wezterm` directory. I would've made a PR myself but I was a bit unfamiliar with the required process and I couldn't figure out if I just needed to call this repo in the `sync_toml` function or if some extra work was required. Hopefully this is not too much work, but if it is I will be glad to do it myself if pointed in the right direction. Thank you so much for your time!

**Comment by wez** [comment]
I have an issue open for updating the sync list, and I've added this to it. It's theoretically trivial, but before adding it, I need to review and reconcile some changes in some of the other schemes to make sure that the version tracking is working correctly for those.

**Comment by wez** [comment]
This is now in wezterm's `main` and will show up in night builds within about an hour.
Thanks!
